export const HERO_SLIDES_DATA = [
  {
    title: 'The New Rules of Streetwear',
    subtitle: 'Fall/Winter 2026 Collection. Engineered silhouettes, architectural tailoring, and 500gsm heavyweight luxury cotton.',
    badge_text: 'FW26 COLLECTION',
    cta_text: 'Shop Streetwear',
    cta_link: '/shop',
    cta_secondary_text: 'Best Sellers',
    cta_secondary_link: '/shop?sort=popular',
    image_url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=1920&q=85&auto=format&fit=crop',
    overlay_color: 'linear-gradient(90deg, rgba(15,23,42,0.78) 0%, rgba(15,23,42,0.4) 60%, rgba(15,23,42,0.2) 100%)',
    text_color: '#ffffff',
    text_align: 'left',
    sort_order: 1,
    is_active: true,
  },
  {
    title: 'Discover Independent Brand Stores',
    subtitle: 'Explore curated collections from verified underground creators, streetwear ateliers, and independent fashion houses.',
    badge_text: 'MULTI-BRAND MARKETPLACE',
    cta_text: 'Explore Brand Stores',
    cta_link: '/stores',
    cta_secondary_text: 'View All Pieces',
    cta_secondary_link: '/shop',
    image_url: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1920&q=85&auto=format&fit=crop',
    overlay_color: 'rgba(15,23,42,0.65)',
    text_color: '#ffffff',
    text_align: 'center',
    sort_order: 2,
    is_active: true,
  },
  {
    title: 'Heavyweight Fleece & Signature Hoodies',
    subtitle: 'Ultra-dense 500gsm French terry with brushed interiors, double-layered hoods, and relaxed drop-shoulder profiles.',
    badge_text: '500GSM HEAVYWEIGHT',
    cta_text: 'Shop Hoodies',
    cta_link: '/shop?category=hoodies',
    cta_secondary_text: 'Limited Drops',
    cta_secondary_link: '/shop?category=limited-edition',
    image_url: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=1920&q=85&auto=format&fit=crop',
    overlay_color: 'linear-gradient(90deg, rgba(15,23,42,0.75) 0%, rgba(15,23,42,0.3) 100%)',
    text_color: '#ffffff',
    text_align: 'left',
    sort_order: 3,
    is_active: true,
  },
  {
    title: 'Cyber Tokyo: Shibuya Underdrive',
    subtitle: 'Neo-futuristic Tokyo typography and cyberpunk graphics forged for the night wandering collective.',
    badge_text: 'FEATURED STORE SPOTLIGHT',
    cta_text: 'Visit Cyber Tokyo',
    cta_link: '/store/cyber-tokyo',
    cta_secondary_text: 'All Stores',
    cta_secondary_link: '/stores',
    image_url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1920&q=85&auto=format&fit=crop',
    overlay_color: 'linear-gradient(270deg, rgba(15,23,42,0.85) 0%, rgba(88,28,135,0.45) 50%, rgba(15,23,42,0.3) 100%)',
    text_color: '#ffffff',
    text_align: 'right',
    sort_order: 4,
    is_active: true,
  },
  {
    title: 'Acid Washes & Statement Graphic Tees',
    subtitle: 'Distressed vintage textures, hand-drawn typography, and high-density screen-prints that never fade.',
    badge_text: 'VINTAGE & GRAPHIC TEES',
    cta_text: 'Shop Graphic Tees',
    cta_link: '/shop?category=graphic-tees',
    cta_secondary_text: 'New In Archive',
    cta_secondary_link: '/shop?category=new-arrivals',
    image_url: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=1920&q=85&auto=format&fit=crop',
    overlay_color: 'linear-gradient(90deg, rgba(15,23,42,0.75) 0%, rgba(15,23,42,0.3) 100%)',
    text_color: '#ffffff',
    text_align: 'left',
    sort_order: 5,
    is_active: true,
  },
  {
    title: 'Apex: Technical Wear For The Transit',
    subtitle: 'Weatherproof ripstop fabrics, modular cargo pockets, and ergonomic utility apparel engineered for motion.',
    badge_text: 'TECHNICAL STREET CULTURE',
    cta_text: 'Shop Apex Store',
    cta_link: '/store/apex-streetwear',
    cta_secondary_text: 'All Outerwear',
    cta_secondary_link: '/shop?category=outerwear',
    image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=1920&q=85&auto=format&fit=crop',
    overlay_color: 'rgba(15,23,42,0.65)',
    text_color: '#ffffff',
    text_align: 'center',
    sort_order: 6,
    is_active: true,
  },
  {
    title: 'Limited Edition Serialized Vault',
    subtitle: 'Strictly limited release quantities with verified archival serial numbers. Once sold out, never reproduced.',
    badge_text: 'LIMITED ARCHIVE VAULT',
    cta_text: 'Unlock The Vault',
    cta_link: '/shop?category=limited-edition',
    cta_secondary_text: 'Track Order',
    cta_secondary_link: '/track',
    image_url: 'https://images.unsplash.com/photo-1523381294911-8d3cead13475?w=1920&q=85&auto=format&fit=crop',
    overlay_color: 'linear-gradient(90deg, rgba(15,23,42,0.8) 0%, rgba(15,23,42,0.35) 100%)',
    text_color: '#ffffff',
    text_align: 'left',
    sort_order: 7,
    is_active: true,
  },
  {
    title: 'Cold Weather Puffers & Thermal Coats',
    subtitle: 'Thermal down insulation and weather-sealed shells designed for urban climates with minimalist proportions.',
    badge_text: 'WINTER INSULATION',
    cta_text: 'Shop Outerwear',
    cta_link: '/shop?category=outerwear',
    cta_secondary_text: 'Shop All',
    cta_secondary_link: '/shop',
    image_url: 'https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=1920&q=85&auto=format&fit=crop',
    overlay_color: 'linear-gradient(270deg, rgba(15,23,42,0.8) 0%, rgba(15,23,42,0.25) 100%)',
    text_color: '#ffffff',
    text_align: 'right',
    sort_order: 8,
    is_active: true,
  },
  {
    title: 'Vortex Athletics: Kinetic Motion',
    subtitle: 'Where performance sportswear meets luxury streetwear comfort. Seamless movement for athletes and creators.',
    badge_text: 'ATHLETIC LUXURY',
    cta_text: 'Shop Vortex Store',
    cta_link: '/store/vortex-athletics',
    cta_secondary_text: 'Explore Brands',
    cta_secondary_link: '/stores',
    image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=1920&q=85&auto=format&fit=crop',
    overlay_color: 'rgba(15,23,42,0.65)',
    text_color: '#ffffff',
    text_align: 'center',
    sort_order: 9,
    is_active: true,
  },
  {
    title: 'Sell Your Brand on Menyphis',
    subtitle: 'Join Pakistan\'s premier curated streetwear marketplace. Dedicated brand storefront, automated payouts, and nationwide reach.',
    badge_text: 'BECOME A SELLER',
    cta_text: 'Apply for Brand Store',
    cta_link: '/become-a-seller',
    cta_secondary_text: 'Brand Directory',
    cta_secondary_link: '/stores',
    image_url: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=1920&q=85&auto=format&fit=crop',
    overlay_color: 'linear-gradient(90deg, rgba(15,23,42,0.85) 0%, rgba(79,70,229,0.35) 60%, rgba(15,23,42,0.3) 100%)',
    text_color: '#ffffff',
    text_align: 'left',
    sort_order: 10,
    is_active: true,
  },
];
